steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-f'
      - 'Dockerfile.demo'
      - '-t'
      - 'gcr.io/$PROJECT_ID/cleveria-demo'
      - '.'
images:
  - 'gcr.io/$PROJECT_ID/cleveria-demo'
